import { normalizers, type NormalizerName } from './normalizers';

export interface SurveyField {
  key: string;
  label: string;
  type: 'text' | 'number' | 'tel' | 'email' | 'url' | 'currency' | 'percent' | 'checkbox';
  required?: boolean;
  placeholder?: string;
  /** Hide this field when the field with this key is truthy */
  hideWhen?: string;
  /** Half-width in the grid layout */
  half?: boolean;
  /**
   * Named normalizer applied server-side at write-time, before persisting to
   * the sheet. See `normalizers.ts` for the available names.
   */
  normalize?: NormalizerName;
}

export interface SurveySection {
  title: string;
  description?: string;
  /**
   * - 'percentage_group': fields are percent inputs that should sum to 100
   * - 'disciplines_group': checkbox fields; at least one must be checked
   */
  type?: 'percentage_group' | 'disciplines_group';
  fields: SurveyField[];
}

export interface SurveyTemplate {
  id: string;
  name: string;
  sections: SurveySection[];
}

/**
 * Resolve template strings like {{prevYear}} based on survey year.
 */
export function resolveLabel(label: string, surveyYear: number): string {
  return label
    .replace(/\{\{year\}\}/g, String(surveyYear))
    .replace(/\{\{prevYear\}\}/g, String(surveyYear - 1))
    .replace(/\{\{prevYear-1\}\}/g, String(surveyYear - 2))
    .replace(/\{\{prevYear-2\}\}/g, String(surveyYear - 3));
}

export const architectSurveyTemplate: SurveyTemplate = {
  id: 'architects',
  name: 'Top Utah Architects Survey',
  sections: [
    {
      title: 'General Company Information',
      fields: [
        { key: 'firm_name', label: 'Name of Firm', type: 'text', required: true, normalize: 'trim' },
        { key: 'location', label: 'Location', type: 'text', required: true, half: true, normalize: 'trim' },
        { key: 'year_founded', label: 'Year Founded', type: 'number', required: true, half: true },
        { key: 'top_executive', label: 'Top Executive', type: 'text', required: true, half: true, normalize: 'trim' },
        { key: 'top_executive_title', label: 'Title', type: 'text', required: true, half: true, normalize: 'trim' },
        { key: 'years_at_firm', label: 'Years at Firm', type: 'number', required: true, half: true },
        { key: 'address', label: 'Address', type: 'text', required: true, normalize: 'address' },
        { key: 'city', label: 'City', type: 'text', required: true, half: true, normalize: 'trim' },
        { key: 'state', label: 'State', type: 'text', required: true, half: true, placeholder: 'UT', normalize: 'usState' },
        { key: 'zip', label: 'ZIP', type: 'text', required: true, half: true, normalize: 'trim' },
        { key: 'phone', label: 'Phone', type: 'tel', required: true, half: true, normalize: 'phone' },
        { key: 'marketing_email', label: 'Email of Marketing/BD Manager', type: 'email', required: true, half: true, normalize: 'email' },
        { key: 'website', label: 'Website', type: 'url', required: true, half: true, normalize: 'trim' },
        { key: 'other_locations', label: 'Other Utah Office Locations (city only)', type: 'text', half: true, normalize: 'trim' },
        { key: 'num_employees', label: 'Number of Employees (all Utah offices)', type: 'number', required: true, half: true },
        { key: 'num_licensed_architects', label: '# of Licensed Architects', type: 'number', required: true, half: true },
        { key: 'num_leed_ap', label: '# LEED AP', type: 'number', half: true },
      ],
    },
    {
      title: 'Revenues',
      description: 'Generated by offices located in Utah, in millions, to two decimal places (e.g., enter 47.50 for $47.5 million). Projects outside of Utah billed to Utah-based offices should be included. Revenue figures are used for ranking — the second decimal breaks ties at the hundreds-of-thousands place. Check "Decline to Disclose" to be listed by employee count instead. See last year\'s issue at <a href="https://www.utahcdmag.com/archive#:~:text=june%202025,-VIEW%20ISSUE" target="_blank" rel="noopener noreferrer" class="text-amber-700 underline">utahcdmag.com (June 2025, page 82)</a> to see how the rankings work.',
      fields: [
        { key: 'revenue_current', label: '{{prevYear}} Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_prior_1', label: '{{prevYear-1}} Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_prior_2', label: '{{prevYear-2}} Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_dnd', label: 'Decline to Disclose (DND)', type: 'checkbox' },
      ],
    },
    {
      title: 'Projects',
      fields: [
        { key: 'largest_project_completed', label: 'Largest Utah project completed in {{prevYear}}', type: 'text', half: true, normalize: 'trim' },
        { key: 'largest_project_completed_location', label: 'Location (city only)', type: 'text', half: true, normalize: 'trim' },
        { key: 'largest_project_upcoming', label: 'Largest Utah project to break ground in {{year}}', type: 'text', half: true, normalize: 'trim' },
        { key: 'largest_project_upcoming_location', label: 'Location (city only)', type: 'text', half: true, normalize: 'trim' },
      ],
    },
    {
      title: 'Market Segments',
      description: 'Percentage of revenues from each segment as whole numbers (e.g., enter 25 for 25%). No decimals. The total must equal 100%.',
      type: 'percentage_group',
      fields: [
        { key: 'pct_k12', label: 'K-12', type: 'percent', half: true },
        { key: 'pct_higher_ed', label: 'Higher Education', type: 'percent', half: true },
        { key: 'pct_civic', label: 'Civic/Institutional', type: 'percent', half: true },
        { key: 'pct_healthcare', label: 'Healthcare', type: 'percent', half: true },
        { key: 'pct_office', label: 'Office', type: 'percent', half: true },
        { key: 'pct_resort_hospitality', label: 'Resort/Hospitality', type: 'percent', half: true },
        { key: 'pct_multi_family', label: 'Multi-Family', type: 'percent', half: true },
        { key: 'pct_commercial_retail', label: 'Commercial/Retail', type: 'percent', half: true },
        { key: 'pct_sports_rec', label: 'Sports/Rec', type: 'percent', half: true },
        { key: 'pct_industrial', label: 'Industrial', type: 'percent', half: true },
        { key: 'other_segment_name', label: 'Other (please specify)', type: 'text', half: true, placeholder: 'e.g., Mission Critical', normalize: 'trim' },
        { key: 'pct_other', label: 'Other %', type: 'percent', half: true },
      ],
    },
  ],
};

export const contractorSurveyTemplate: SurveyTemplate = {
  id: 'contractors',
  name: 'Top Utah General Contractor Rankings Survey',
  sections: [
    {
      title: 'General Company Information',
      fields: [
        { key: 'firm_name', label: 'Name of Firm', type: 'text', required: true, normalize: 'trim' },
        { key: 'year_founded', label: 'Year Founded', type: 'number', required: true, half: true },
        { key: 'top_executive', label: 'Top Executive', type: 'text', required: true, half: true, normalize: 'trim' },
        { key: 'top_executive_title', label: 'Title', type: 'text', required: true, half: true, normalize: 'trim' },
        { key: 'years_at_firm', label: 'Years at Firm', type: 'number', required: true, half: true },
        { key: 'address', label: 'Headquarters Address', type: 'text', required: true, normalize: 'address' },
        { key: 'city', label: 'City', type: 'text', required: true, half: true, normalize: 'trim' },
        { key: 'state', label: 'State', type: 'text', required: true, half: true, placeholder: 'UT', normalize: 'usState' },
        { key: 'zip', label: 'ZIP', type: 'text', required: true, half: true, normalize: 'trim' },
        { key: 'phone', label: 'Phone', type: 'tel', required: true, half: true, normalize: 'phone' },
        { key: 'marketing_email', label: 'Email of Marketing/BD Manager', type: 'email', required: true, half: true, normalize: 'email' },
        { key: 'website', label: 'Website', type: 'url', required: true, half: true, normalize: 'trim' },
        { key: 'other_locations', label: 'Other Utah Office Locations (city only)', type: 'text', normalize: 'trim' },
        { key: 'num_employees_ut', label: '# Employees in Utah Offices', type: 'number', required: true, half: true },
        { key: 'num_employees_all', label: '# Employees in All U.S. Offices', type: 'number', required: true, half: true },
      ],
    },
    {
      title: 'Disciplines',
      description:
        'Select the discipline that best describes the majority of work your firm performs. This determines which ranking list by discipline your firm will appear in. For reference, to see last year\'s rankings list <a href="https://irp.cdn-website.com/df545383/files/uploaded/UC-D+july-Aug+2025-spreads.pdf" target="_blank" rel="noopener noreferrer" class="text-amber-700 underline">click the following link</a>.',
      type: 'disciplines_group',
      fields: [
        { key: 'discipline_general_building', label: 'General Building', type: 'checkbox' },
        { key: 'discipline_heavy_highway', label: 'Heavy/Highway', type: 'checkbox' },
        { key: 'discipline_municipal_utility', label: 'Municipal/Utility', type: 'checkbox' },
      ],
    },
    {
      title: 'Revenues',
      description:
        'Utah Construction + Design will rank Utah-based General Contractors in {{year}} in order based on the previous year\'s revenues ({{prevYear}}) generated by firm offices located in Utah. Projects outside of Utah that are billed to Utah-based offices can be included. Firms who choose not to disclose revenues (DND) will be listed after revenue-disclosing firms in order per number of employees.<br /><br />' +
        '<strong>WE WILL PUBLISH THE FOLLOWING LISTS:</strong><br />' +
        '· Top Overall General Contractors (revenues from Utah-based offices only)<br />' +
        '· Top Overall General Contractors (overall revenues, including offices outside Utah)<br />' +
        '· Top General Building Contractors<br />' +
        '· Top Heavy/Highway &amp; Municipal/Utility Contractors<br /><br />' +
        'Companies that supply aggregate products or other supplies should NOT list those revenues; this list is for work as a general contractor. ALSO, firms with headquarters outside Utah will be listed at the bottom of the overall revenue list.<br /><br />' +
        'Annual revenues in millions, to two decimal places (e.g., enter 47.50 for $47.5 million). Report Utah office revenues and All U.S. office revenues separately. If your firm only has offices in Utah, leave the "All U.S." fields blank. Revenue figures are used for ranking — the second decimal breaks ties at the hundreds-of-thousands place. Check "Decline to Disclose" to be listed by employee count instead.',
      fields: [
        { key: 'revenue_ut_current', label: '{{prevYear}} Utah Office Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_all_current', label: '{{prevYear}} All U.S. Offices Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_ut_prior_1', label: '{{prevYear-1}} Utah Office Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_all_prior_1', label: '{{prevYear-1}} All U.S. Offices Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_ut_prior_2', label: '{{prevYear-2}} Utah Office Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_all_prior_2', label: '{{prevYear-2}} All U.S. Offices Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_dnd', label: 'Decline to Disclose (DND)', type: 'checkbox' },
      ],
    },
    {
      title: 'Projects',
      fields: [
        { key: 'largest_project_completed', label: 'Largest Utah project completed in {{prevYear}}', type: 'text', half: true, normalize: 'trim' },
        { key: 'largest_project_completed_location', label: 'Location (city only)', type: 'text', half: true, normalize: 'trim' },
        { key: 'largest_project_upcoming', label: 'Largest Utah project started in {{year}}', type: 'text', half: true, normalize: 'trim' },
        { key: 'largest_project_upcoming_location', label: 'Location (city only)', type: 'text', half: true, normalize: 'trim' },
      ],
    },
    {
      title: 'Top Markets',
      description: 'Percentage of revenues from each market segment as whole numbers (e.g., enter 25 for 25%). No decimals. The total must equal 100%.',
      type: 'percentage_group',
      fields: [
        { key: 'pct_k12', label: 'K-12', type: 'percent', half: true },
        { key: 'pct_higher_ed', label: 'Higher Education', type: 'percent', half: true },
        { key: 'pct_civic', label: 'Civic/Institutional', type: 'percent', half: true },
        { key: 'pct_healthcare', label: 'Healthcare', type: 'percent', half: true },
        { key: 'pct_multi_family', label: 'Multi-Family', type: 'percent', half: true },
        { key: 'pct_commercial_retail', label: 'Commercial/Retail', type: 'percent', half: true },
        { key: 'pct_industrial', label: 'Industrial', type: 'percent', half: true },
        { key: 'pct_resort_hospitality', label: 'Resort/Hospitality', type: 'percent', half: true },
        { key: 'pct_sports_rec', label: 'Sports/Rec', type: 'percent', half: true },
        { key: 'pct_religious', label: 'Religious', type: 'percent', half: true },
        { key: 'pct_underground', label: 'Underground', type: 'percent', half: true },
        { key: 'pct_telecomm', label: 'Telecomm', type: 'percent', half: true },
        { key: 'pct_wastewater', label: 'Wastewater', type: 'percent', half: true },
        { key: 'pct_heavy_civil', label: 'Heavy Civil', type: 'percent', half: true },
        { key: 'pct_water', label: 'Water', type: 'percent', half: true },
        { key: 'pct_highway', label: 'Highway', type: 'percent', half: true },
        { key: 'pct_oil_gas', label: 'Oil & Gas', type: 'percent', half: true },
        { key: 'pct_power', label: 'Power', type: 'percent', half: true },
        { key: 'other_segment_name', label: 'Other (please specify)', type: 'text', half: true, placeholder: 'e.g., Mission Critical', normalize: 'trim' },
        { key: 'pct_other', label: 'Other %', type: 'percent', half: true },
      ],
    },
  ],
};

export const surveyTemplates: Record<string, SurveyTemplate> = {
  architects: architectSurveyTemplate,
  contractors: contractorSurveyTemplate,
};

/**
 * Apply each field's named normalizer to the submission data. Returns a new
 * object — does not mutate the input. Fields without a `normalize` tag, or
 * keys not present in `data`, are left untouched.
 *
 * Called server-side from the responses POST route. Centralizing this at the
 * write boundary means any path that reaches the sheet (form submit, draft
 * restore, edit) gets the same cleaning.
 */
export function normalizeSubmission(
  template: SurveyTemplate,
  data: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...data };
  for (const section of template.sections) {
    for (const field of section.fields) {
      if (field.normalize && field.key in out) {
        out[field.key] = normalizers[field.normalize](out[field.key]);
      }
    }
  }
  return out;
}
