export interface SurveyField {
  key: string;
  label: string;
  type: 'text' | 'number' | 'tel' | 'email' | 'url' | 'currency' | 'percent' | 'checkbox';
  required?: boolean;
  placeholder?: string;
  /** Hide this field when the field with this key is truthy */
  hideWhen?: string;
  /** Half-width in the grid layout */
  half?: boolean;
}

export interface SurveySection {
  title: string;
  description?: string;
  /** If 'percentage_group', fields are percent inputs that should sum to 100 */
  type?: 'percentage_group';
  fields: SurveyField[];
}

export interface SurveyTemplate {
  id: string;
  name: string;
  sections: SurveySection[];
}

/**
 * Resolve template strings like {{prevYear}} based on survey year.
 */
export function resolveLabel(label: string, surveyYear: number): string {
  return label
    .replace(/\{\{year\}\}/g, String(surveyYear))
    .replace(/\{\{prevYear\}\}/g, String(surveyYear - 1))
    .replace(/\{\{prevYear-1\}\}/g, String(surveyYear - 2))
    .replace(/\{\{prevYear-2\}\}/g, String(surveyYear - 3));
}

export const architectSurveyTemplate: SurveyTemplate = {
  id: 'architects',
  name: 'Top Utah Architects Survey',
  sections: [
    {
      title: 'General Company Information',
      fields: [
        { key: 'firm_name', label: 'Name of Firm', type: 'text', required: true },
        { key: 'location', label: 'Location', type: 'text', required: true, half: true },
        { key: 'year_founded', label: 'Year Founded', type: 'number', required: true, half: true },
        { key: 'top_executive', label: 'Top Executive', type: 'text', required: true, half: true },
        { key: 'top_executive_title', label: 'Title', type: 'text', required: true, half: true },
        { key: 'years_at_firm', label: 'Years at Firm', type: 'number', half: true },
        { key: 'address', label: 'Address', type: 'text', required: true },
        { key: 'city', label: 'City', type: 'text', required: true, half: true },
        { key: 'state', label: 'State', type: 'text', required: true, half: true, placeholder: 'UT' },
        { key: 'zip', label: 'ZIP', type: 'text', required: true, half: true },
        { key: 'phone', label: 'Phone', type: 'tel', required: true, half: true },
        { key: 'marketing_email', label: 'Email of Marketing/BD Manager', type: 'email', half: true },
        { key: 'website', label: 'Website', type: 'url', half: true },
        { key: 'other_locations', label: 'Other Utah Office Locations', type: 'text', half: true },
        { key: 'num_employees', label: 'Number of Employees (all Utah offices)', type: 'number', required: true, half: true },
        { key: 'num_licensed_architects', label: '# of Licensed Architects', type: 'number', half: true },
        { key: 'num_leed_ap', label: '# LEED AP', type: 'number', half: true },
      ],
    },
    {
      title: 'Revenues',
      description: 'Generated by offices located in Utah, in millions (e.g., enter 47.5 for $47.5M). Revenue figures are used for ranking. Check "Decline to Disclose" to be listed by employee count instead.',
      fields: [
        { key: 'revenue_dnd', label: 'Decline to Disclose (DND)', type: 'checkbox' },
        { key: 'revenue_current', label: '{{prevYear}} Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_prior_1', label: '{{prevYear-1}} Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
        { key: 'revenue_prior_2', label: '{{prevYear-2}} Revenue (millions)', type: 'currency', hideWhen: 'revenue_dnd', half: true },
      ],
    },
    {
      title: 'Projects',
      fields: [
        { key: 'largest_project_completed', label: 'Largest Project completed in {{prevYear}} (include location)', type: 'text' },
        { key: 'largest_project_upcoming', label: 'Largest Project to break ground in {{year}} (include location)', type: 'text' },
      ],
    },
    {
      title: 'Market Segments',
      description: 'Percentage of revenues from each segment. Should total 100%.',
      type: 'percentage_group',
      fields: [
        { key: 'pct_k12', label: 'K-12', type: 'percent', half: true },
        { key: 'pct_higher_ed', label: 'Higher Education', type: 'percent', half: true },
        { key: 'pct_civic', label: 'Civic/Institutional', type: 'percent', half: true },
        { key: 'pct_healthcare', label: 'Healthcare', type: 'percent', half: true },
        { key: 'pct_office', label: 'Office', type: 'percent', half: true },
        { key: 'pct_resort_hospitality', label: 'Resort/Hospitality', type: 'percent', half: true },
        { key: 'pct_multi_family', label: 'Multi-Family', type: 'percent', half: true },
        { key: 'pct_commercial_retail', label: 'Commercial/Retail', type: 'percent', half: true },
        { key: 'pct_sports_rec', label: 'Sports/Rec', type: 'percent', half: true },
        { key: 'pct_industrial', label: 'Industrial', type: 'percent', half: true },
        { key: 'pct_other', label: 'Other', type: 'percent', half: true },
      ],
    },
  ],
};

export const surveyTemplates: Record<string, SurveyTemplate> = {
  architects: architectSurveyTemplate,
};
